### ISSUE TITLE
Android Version below 5.0

### ISSUE THREAD

**Issue by ibu2710** [Aniruddha-Tapas/Document-Scanner#2]
Will the Library work on devices below 5.0... Can i make it run on 5.0 below android devices. Please Help Me

**Comment by Aniruddha-Tapas** [comment]
Yes this Document Scanner app can work for devices below Android 5 0. The only change you need to incorporate is to use the OpenCV for Android library with version less than 3.1.0 for e.g. 2.4.3. Then the app can run on those devices. Due to the high end version v3.1.0 of OpenCV integerated in the app, it needs to run on Android 5.0 (lollipop) or newer.
